// Copyright (c) 2017 The Alvalor Authors
//
// This file is part of Alvalor.
//
// Alvalor is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Alvalor is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with Alvalor.  If not, see <http://www.gnu.org/licenses/>.

package network

import (
	"net"
)

// Tick is a type of event that is generated by a clock.
type Tick struct {
	Mask uint64
}

// Command is a type of event that contains an external command.
type Command struct {
	Source string
	Value  interface{}
}

// Networking is a type of event that describes a networking event.
type Networking struct {
	Address string
	Value   interface{}
}

// Failure represents a connection failure event on a given address.
type Failure struct {
	Address string
}

// Violation represents an invalid peer on a given address.
type Violation struct {
	Address string
}

// Error represens a messaging error on a given address.
type Error struct {
	Address string
}

// Connection represents a connection event on a given address.
type Connection struct {
	Address string
	Conn    net.Conn
	Nonce   []byte
}

// Disconnection represents a disconnection event on a given address.
type Disconnection struct {
	Address string
}
