// Code generated by capnpc-go.

package proto

// AUTO GENERATED - DO NOT EDIT

import (
	capnp "zombiezen.com/go/capnproto2"
	text "zombiezen.com/go/capnproto2/encoding/text"
	schemas "zombiezen.com/go/capnproto2/schemas"
)

type Discover struct{ capnp.Struct }

// Discover_TypeID is the unique identifier for the type Discover.
const Discover_TypeID = 0x8aec40e836a6b678

func NewDiscover(s *capnp.Segment) (Discover, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Discover{st}, err
}

func NewRootDiscover(s *capnp.Segment) (Discover, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Discover{st}, err
}

func ReadRootDiscover(msg *capnp.Message) (Discover, error) {
	root, err := msg.RootPtr()
	return Discover{root.Struct()}, err
}

func (s Discover) String() string {
	str, _ := text.Marshal(0x8aec40e836a6b678, s.Struct)
	return str
}

// Discover_List is a list of Discover.
type Discover_List struct{ capnp.List }

// NewDiscover creates a new list of Discover.
func NewDiscover_List(s *capnp.Segment, sz int32) (Discover_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return Discover_List{l}, err
}

func (s Discover_List) At(i int) Discover { return Discover{s.List.Struct(i)} }

func (s Discover_List) Set(i int, v Discover) error { return s.List.SetStruct(i, v.Struct) }

// Discover_Promise is a wrapper for a Discover promised by a client call.
type Discover_Promise struct{ *capnp.Pipeline }

func (p Discover_Promise) Struct() (Discover, error) {
	s, err := p.Pipeline.Struct()
	return Discover{s}, err
}

const schema_96fc5818637eebba = "x\xda\x12\x98\xe1\xc0d\xc8Z\xcf\xc2\xc0\x10h\xc2\xca" +
	"\xf6\xbfb\xdb2\xb3\x17\x0eo\xba\x18\x04E\x19\xff\xef" +
	"z]\x97,\x11\xf1g\x1a\x03\x0b;\x03\x83\xb0*\xd3" +
	"'aC&v\x86\xf6\xff\x05E\xf9%\xf9\xfa)\x99" +
	"L\xc5\xc9\xf9e\xa9Ez\xc9\x89\x05y\x05V.\x99" +
	"\xc5\xf2`~\x00## \x00\x00\xff\xff\xc3\xbd\x1c\x81"

func init() {
	schemas.Register(schema_96fc5818637eebba,
		0x8aec40e836a6b678)
}
