// Code generated by capnpc-go. DO NOT EDIT.

package codec

import (
	capnp "zombiezen.com/go/capnproto2"
	text "zombiezen.com/go/capnproto2/encoding/text"
	schemas "zombiezen.com/go/capnproto2/schemas"
)

type Discover struct{ capnp.Struct }

// Discover_TypeID is the unique identifier for the type Discover.
const Discover_TypeID = 0x8aec40e836a6b678

func NewDiscover(s *capnp.Segment) (Discover, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Discover{st}, err
}

func NewRootDiscover(s *capnp.Segment) (Discover, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Discover{st}, err
}

func ReadRootDiscover(msg *capnp.Message) (Discover, error) {
	root, err := msg.RootPtr()
	return Discover{root.Struct()}, err
}

func (s Discover) String() string {
	str, _ := text.Marshal(0x8aec40e836a6b678, s.Struct)
	return str
}

// Discover_List is a list of Discover.
type Discover_List struct{ capnp.List }

// NewDiscover creates a new list of Discover.
func NewDiscover_List(s *capnp.Segment, sz int32) (Discover_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return Discover_List{l}, err
}

func (s Discover_List) At(i int) Discover { return Discover{s.List.Struct(i)} }

func (s Discover_List) Set(i int, v Discover) error { return s.List.SetStruct(i, v.Struct) }

func (s Discover_List) String() string {
	str, _ := text.MarshalList(0x8aec40e836a6b678, s.List)
	return str
}

// Discover_Promise is a wrapper for a Discover promised by a client call.
type Discover_Promise struct{ *capnp.Pipeline }

func (p Discover_Promise) Struct() (Discover, error) {
	s, err := p.Pipeline.Struct()
	return Discover{s}, err
}

const schema_96fc5818637eebba = "x\xda2\x90ft`2d\x9d\xcf\xc1\xc0\x10\x98\xc2" +
	"\xca\xf6\xbfb\xdb2\xb3\x17\x0eo\xba\x18\x04\xf9\x19\xff" +
	"\xefz]\x97,\x11\xf1g\x1a\x03\x0b;\x03\x83\xb0)" +
	"\xcb!a[\x16v\x86\xff\x0c\xdc\xffS2\x8b\x93\xf3" +
	"\xcbR\x8b\x98\xf4\x92\x13\x0b\xf2\x0a\xac\\\xa0|\x86\x00" +
	"FF@\x00\x00\x00\xff\xff?\x12\x1ad"

func init() {
	schemas.Register(schema_96fc5818637eebba,
		0x8aec40e836a6b678)
}
