// Code generated by capnpc-go. DO NOT EDIT.

package codec

import (
	capnp "zombiezen.com/go/capnproto2"
	text "zombiezen.com/go/capnproto2/encoding/text"
	schemas "zombiezen.com/go/capnproto2/schemas"
)

type Fee struct{ capnp.Struct }

// Fee_TypeID is the unique identifier for the type Fee.
const Fee_TypeID = 0xcda91da91de91079

func NewFee(s *capnp.Segment) (Fee, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Fee{st}, err
}

func NewRootFee(s *capnp.Segment) (Fee, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Fee{st}, err
}

func ReadRootFee(msg *capnp.Message) (Fee, error) {
	root, err := msg.RootPtr()
	return Fee{root.Struct()}, err
}

func (s Fee) String() string {
	str, _ := text.Marshal(0xcda91da91de91079, s.Struct)
	return str
}

func (s Fee) From() ([]byte, error) {
	p, err := s.Struct.Ptr(0)
	return []byte(p.Data()), err
}

func (s Fee) HasFrom() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s Fee) SetFrom(v []byte) error {
	return s.Struct.SetData(0, v)
}

func (s Fee) Amount() uint64 {
	return s.Struct.Uint64(0)
}

func (s Fee) SetAmount(v uint64) {
	s.Struct.SetUint64(0, v)
}

// Fee_List is a list of Fee.
type Fee_List struct{ capnp.List }

// NewFee creates a new list of Fee.
func NewFee_List(s *capnp.Segment, sz int32) (Fee_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return Fee_List{l}, err
}

func (s Fee_List) At(i int) Fee { return Fee{s.List.Struct(i)} }

func (s Fee_List) Set(i int, v Fee) error { return s.List.SetStruct(i, v.Struct) }

func (s Fee_List) String() string {
	str, _ := text.MarshalList(0xcda91da91de91079, s.List)
	return str
}

// Fee_Promise is a wrapper for a Fee promised by a client call.
type Fee_Promise struct{ *capnp.Pipeline }

func (p Fee_Promise) Struct() (Fee, error) {
	s, err := p.Pipeline.Struct()
	return Fee{s}, err
}

const schema_909e243e4566f5a3 = "x\xda$\xc8?\x0e\xc1P\x00\x06\xf0\xef{}E%" +
	"\x0dRk\xd3\xa5\x03\x12R\x89\xa9\x03\x16\xd6zGh" +
	"\xe4u\xd2?i\x888\x84\x84\x0bXL=\x8c\x838" +
	"\x80\xf9\x89\xd8~\xf9E\x09\xd7bn'\x0e\xa0\x0ev" +
	"\xcb\\\xfao\xbf\xf1\x9b\x17T\x974\xcfO\xb6Y\x86" +
	"\x8f\x1bl\xb6\x01\xef*k\xef.\xff:\xc3 0\x99" +
	"\xd6\xb3}Z\x15\x08\xaax\xab\xf5\x8eT\x1dK\x02\x92" +
	"\xc0`<\x01ThQE\x82\xe4\x90\xbf\x9b\xc6\x80\x1a" +
	"YT\x0b\xc1^V\x979]\x08\xba\xe0*\xcd\xcbS" +
	"q\xa4\x03A\x07\xfc\x06\x00\x00\xff\xff\xa1\xf4\x1en"

func init() {
	schemas.Register(schema_909e243e4566f5a3,
		0xcda91da91de91079)
}
