// Code generated by capnpc-go. DO NOT EDIT.

package codec

import (
	capnp "zombiezen.com/go/capnproto2"
	text "zombiezen.com/go/capnproto2/encoding/text"
	schemas "zombiezen.com/go/capnproto2/schemas"
)

type Pong struct{ capnp.Struct }

// Pong_TypeID is the unique identifier for the type Pong.
const Pong_TypeID = 0xe5b532ff4fa02dff

func NewPong(s *capnp.Segment) (Pong, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Pong{st}, err
}

func NewRootPong(s *capnp.Segment) (Pong, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Pong{st}, err
}

func ReadRootPong(msg *capnp.Message) (Pong, error) {
	root, err := msg.RootPtr()
	return Pong{root.Struct()}, err
}

func (s Pong) String() string {
	str, _ := text.Marshal(0xe5b532ff4fa02dff, s.Struct)
	return str
}

func (s Pong) Nonce() uint32 {
	return s.Struct.Uint32(0)
}

func (s Pong) SetNonce(v uint32) {
	s.Struct.SetUint32(0, v)
}

// Pong_List is a list of Pong.
type Pong_List struct{ capnp.List }

// NewPong creates a new list of Pong.
func NewPong_List(s *capnp.Segment, sz int32) (Pong_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return Pong_List{l}, err
}

func (s Pong_List) At(i int) Pong { return Pong{s.List.Struct(i)} }

func (s Pong_List) Set(i int, v Pong) error { return s.List.SetStruct(i, v.Struct) }

func (s Pong_List) String() string {
	str, _ := text.MarshalList(0xe5b532ff4fa02dff, s.List)
	return str
}

// Pong_Promise is a wrapper for a Pong promised by a client call.
type Pong_Promise struct{ *capnp.Pipeline }

func (p Pong_Promise) Struct() (Pong, error) {
	s, err := p.Pipeline.Struct()
	return Pong{s}, err
}

const schema_cf51decd769a7cb5 = "x\xda\x12X\xe6\xc0d\xc8Z\xcf\xc2\xc0\x10h\xc2\xca" +
	"\xf6\xff\xbf\xee\x02\xff\xffF[\x9f2\x04r32\xfe" +
	"\xdfZ3\xab\xec\xec\xbd\xc0\xf3\x0c,\xec\x0c\x0c\xc2\xaa" +
	"LM\xc2\x9aL\x10\x96=C\xeb\xff\x82\xfc\xbct\xbd" +
	"\xe4\xc4\x02\xc6\xbc\x02\xab\x80\xfc\xbct\x86\x00F\xc6@" +
	"\x16f\x16\x06\x06\x16F\x06\x06A^#\x06\x86@\x0e" +
	"f\xc6@\x11&F\xf9\xbc\xfc\xbc\xe4TF\x0e\x06&" +
	"F\x0e\x06F@\x00\x00\x00\xff\xff\x84\xf1\x1bk"

func init() {
	schemas.Register(schema_cf51decd769a7cb5,
		0xe5b532ff4fa02dff)
}
